src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views import defaults as default_views

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

base_urlpatterns = [
    path("users/", include("rard.users.urls", namespace="users")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    # research urls
    path("", include("rard.research.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    base_urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        base_urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + base_urlpatterns

prefix = getattr(settings, "URL_PREFIX", "")


urlpatterns = [path("{}".format(prefix), include((base_urlpatterns)))]

src/rard/research/urls.py
from django.conf.urls import include
from django.urls import path

import rard.research.views as views

# common urls for both fragments and testimonia for shared views that we
# want to expose under different namespaces
common_patterns = [
    path(
        "original-text/<pk>/update/",
        views.OriginalTextUpdateView.as_view(),
        name="update_original_text",
    ),
    path(
        "original-text/<pk>/update-author/",
        views.OriginalTextUpdateAuthorView.as_view(),
        name="update_author_original_text",
    ),
    path(
        "original-text/<pk>/delete/",
        views.OriginalTextDeleteView.as_view(),
        name="delete_original_text",
    ),
    path(
        "original-text/<pk>/create-translation/",
        views.TranslationCreateView.as_view(),
        name="create_translation",
    ),
    path(
        "translation/<pk>/update/",
        views.TranslationUpdateView.as_view(),
        name="update_translation",
    ),
    path(
        "translation/<pk>/delete/",
        views.TranslationDeleteView.as_view(),
        name="delete_translation",
    ),
]

# history_patterns = [
#     path("<content_type>/<pk>/history/", views.HistoryView.as_view(), name="history"),
# ]

# app_name = "research"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("ajax/move-link/", views.MoveLinkView.as_view(), name="move_link"),
    path("ajax/move-topic/", views.MoveTopicView.as_view(), name="move_topic"),
    path(
        "ajax/move-anonymoustopiclink/",
        views.MoveAnonymousTopicLinkView.as_view(),
        name="move_anonymoustopiclink",
    ),
    path(
        "ajax/create-apparatus-criticus-line/",
        views.CreateApparatusCriticusLineView.as_view(),
        name="create_apparatus_criticus_line",
    ),
    path(
        "ajax/delete-apparatus-criticus-line/",
        views.DeleteApparatusCriticusLineView.as_view(),
        name="delete_apparatus_criticus_line",
    ),
    path(
        "ajax/update-apparatus-criticus-line/",
        views.UpdateApparatusCriticusLineView.as_view(),
        name="update_apparatus_criticus_line",
    ),
    path(
        "ajax/refresh-original-text-content/",
        views.RefreshOriginalTextContentView.as_view(),
        name="refresh_original_text_content",
    ),
    # path("comment/<pk>/delete/", views.CommentDeleteView.as_view(), name="delete_comment"),
    # path("text-field/<pk>/comments/", views.TextObjectFieldCommentListView.as_view(), name="list_comments_on_text"),
    path(
        "antiquarian/",
        include(
            (
                [
                    path("list/", views.AntiquarianListView.as_view(), name="list"),
                    path(
                        "create/", views.AntiquarianCreateView.as_view(), name="create"
                    ),
                    path("<pk>/", views.AntiquarianDetailView.as_view(), name="detail"),
                    path(
                        "<pk>/introduction/",
                        views.AntiquarianIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/",
                        views.AntiquarianUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.AntiquarianUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "<pk>/bibliography/",
                        views.BibliographySectionView.as_view(),
                        name="bibliography",
                    ),
                    path(
                        "<pk>/refresh_bibliography/",
                        views.refresh_bibliography_from_mentions,
                        name="refresh_bibliography",
                    ),
                    path(
                        "<pk>/delete/",
                        views.AntiquarianDeleteView.as_view(),
                        name="delete",
                    ),
                    path(
                        "<pk>/work/create/",
                        views.AntiquarianWorkCreateView.as_view(),
                        name="create_work",
                    ),
                    path(
                        "<pk>/works/",
                        views.AntiquarianWorksUpdateView.as_view(),
                        name="update_works",
                    ),
                    path(
                        "<pk>/bibliography/create/",
                        views.BibliographyCreateView.as_view(),
                        name="create_bibliography",
                    ),
                    path(
                        "concordance/<pk>/delete/",
                        views.AntiquarianConcordanceDeleteView.as_view(),
                        name="delete_concordance",
                    ),
                ],
                "research",
            ),
            namespace="antiquarian",
        ),
    ),
    path(
        "bibliography/",
        include(
            (
                [
                    path("", views.BibliographyOverviewView.as_view(), name="overview"),
                    path("list/", views.BibliographyListView.as_view(), name="list"),
                    path(
                        "create/",
                        views.BibliographyCreateView.as_view(),
                        name="create",
                    ),
                    path(
                        "create-inline/",
                        views.BibliographyCreateInlineView.as_view(),
                        name="create_inline",
                    ),
                    path(
                        "<pk>/",
                        views.BibliographyDetailView.as_view(),
                        name="detail",
                    ),
                    path(
                        "<pk>/update/",
                        views.BibliographyUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/delete/",
                        views.BibliographyDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "research",
            ),
            namespace="bibliography",
        ),
    ),
    path(
        "work/",
        include(
            (
                [
                    path("list/", views.WorkListView.as_view(), name="list"),
                    path("create/", views.WorkCreateView.as_view(), name="create"),
                    path("<pk>/", views.WorkDetailView.as_view(), name="detail"),
                    path("<pk>/update/", views.WorkUpdateView.as_view(), name="update"),
                    path("<pk>/delete/", views.WorkDeleteView.as_view(), name="delete"),
                    path(
                        "<pk>/create-book/",
                        views.BookCreateView.as_view(),
                        name="create_book",
                    ),
                    path(
                        "book/<pk>/update/",
                        views.BookUpdateView.as_view(),
                        name="update_book",
                    ),
                    path(
                        "book/<pk>/delete/",
                        views.BookDeleteView.as_view(),
                        name="delete_book",
                    ),
                    path(
                        "book/<pk>/introduction/",
                        views.BookIntroductionView.as_view(),
                        name="book_introduction",
                    ),
                    path(
                        "<pk>/introduction/",
                        views.WorkIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.WorkUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "book/<pk>/update/introduction/",
                        views.BookUpdateIntroductionView.as_view(),
                        name="update_book_introduction",
                    ),
                    path(
                        "fetch-books",
                        views.fetch_books,
                        name="fetch_books",
                    ),
                ],
                "research",
            ),
            namespace="work",
        ),
    ),
    path(
        "fragment/",
        include(
            (
                [
                    path("list/", views.FragmentListView.as_view(), name="list"),
                    path("create/", views.FragmentCreateView.as_view(), name="create"),
                    path(
                        "<pk>/update/",
                        views.FragmentUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "update-link/<pk>",
                        views.FragmentUpdateWorkLinkView.as_view(),
                        name="update_fragment_link",
                    ),
                    path(
                        "<pk>/commentary/",
                        views.FragmentCommentaryView.as_view(),
                        name="commentary",
                    ),
                    path(
                        "<pk>/update/commentary/",
                        views.FragmentUpdateCommentaryView.as_view(),
                        name="update_commentary",
                    ),
                    path(
                        "<pk>/update/public-commentary/",
                        views.FragmentUpdatePublicCommentaryView.as_view(),
                        name="update_public_commentary",
                    ),

src/rard/users/urls.py
from django.urls import path

from rard.users.views import user_detail_view, user_update_view

app_name = "users"
urlpatterns = [
    path("update-profile/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

src/rard/research/models/bibliography.py
import re

from django.db import models
from django.urls import reverse
from simple_history.models import HistoricalRecords

from rard.research.models.mixins import HistoryModelMixin
from rard.utils.basemodel import BaseModel, LockableModel


class BibliographyItem(HistoryModelMixin, LockableModel, BaseModel):
    history = HistoricalRecords()

    def related_lock_object(self):
        # overrides HistoryModelMixin.related_lock_object
        return self

    def __str__(self):
        r = self.author_surnames
        if self.year:
            r += " [" + self.year + "]"
        title = re.sub(r"<[^>]*>", " ", self.title)
        return r + ": " + re.sub(r"\s+", " ", title).strip()

    def get_absolute_url(self):
        return reverse("bibliography:detail", kwargs={"pk": self.pk})

    def mention_citation(self):
        r = self.author_surnames
        if self.year:
            r += " [" + self.year + "]"
        return r.strip()

    class Meta:
        ordering = ["author_surnames", "year"]

    # string containing names of authors
    # e.g. Smith P, Jones M
    # ordering will be done on this field
    authors = models.CharField(max_length=512, blank=False)

    # comma-separated list of surnames of the authors, to be used for
    # ordering the entries in the list
    author_surnames = models.CharField(
        max_length=512,
        default="",
        blank=False,
        help_text="Comma-separated list of surnames to be used for ordering",
    )

    year = models.CharField(
        max_length=512,
        default="",
        blank=True,
        help_text="Optional date info to use for second-order " "sorting e.g. 1500a",
    )

    title = models.TextField(default="", blank=False)

src/rard/research/models/comment.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from rard.users.models import User
from rard.utils.basemodel import BaseModel


class Comment(BaseModel):
    class Meta:
        # most recent first
        ordering = ["-created"]

    # comments can be left on various object types
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    parent = GenericForeignKey()

    user = models.ForeignKey(User, on_delete=models.SET(User.get_sentinel_user))

    content = models.TextField(blank=False)

src/rard/research/models/history.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.dispatch import receiver
from simple_history.signals import post_create_historical_record

from rard.users.models import User


class HistoricalRecordLog(models.Model):
    class Meta:
        ordering = ["history_date"]

    def get_sentinel_user():
        from allauth.utils import get_user_model

        return get_user_model().objects.get_or_create(
            username="deleted", first_name="Deleted", last_name="User"
        )[0]

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    # auto-deletes e.g. when the history records are pruned
    history_record = GenericForeignKey()

    history_user = models.ForeignKey(
        User,
        related_name="history_log",
        default=None,
        null=True,
        on_delete=models.SET(get_sentinel_user),
    )
    history_date = models.DateTimeField(editable=False)


@receiver(post_create_historical_record)
def post_create_historical_record_callback(sender, **kwargs):
    HistoricalRecordLog.objects.create(
        history_record=kwargs.get("history_instance"),
        history_user=kwargs.get("history_user"),
        history_date=kwargs.get("history_date"),
    )

src/rard/research/models/image.py
from django.conf import settings
from django.db import models

from rard.utils.basemodel import BaseModel


class Image(BaseModel):
    title = models.CharField(max_length=128, blank=False)

    description = models.CharField(max_length=128, blank=True)

    credit = models.CharField(max_length=128, blank=True)

    copyright_status = models.CharField(max_length=128, blank=True)

    name_and_attribution = models.CharField(max_length=128, blank=True)

    public_release = models.BooleanField(default=False)

    upload = models.ImageField(upload_to=settings.UPLOAD_FOLDER, blank=False)

    def __str__(self):
        return self.title

src/rard/research/models/reference.py
from django.db import models


class Reference(models.Model):
    # e.g. Jones/James
    editor = models.CharField(max_length=128, blank=True)

    # The value to be used to refer to the position in the text
    # In some cases it will be a dot-separated list of numbers eg. 2.6-8
    reference_position = models.CharField(blank=False, max_length=128)

    original_text = models.ForeignKey(
        "OriginalText",
        on_delete=models.CASCADE,
        default=None,
        related_name="references",
    )

src/rard/templates/research/partials/appositum_anonymous_list_item.html
{# Assumes context objects named 'appositum' and 'anonymous' also 'can_edit' and 'has_object_lock' #}

{% load i18n show_citing_info %}

<div class='rard-list-item d-flex justify-content-between'>
  <div>
      <li class="unstyled">
        <span>
              {% if perms.research.view_fragment %}
                <a href='{% url "anonymous_fragment:detail" anonymous_fragment.pk %}'>{{anonymous_fragment.get_display_name}}</a>
              {% else %}
                {{anonymous_fragment.get_display_name}}
              {% endif %}
            {% include 'research/partials/render_inline_lock_icon.html' with object=appositum %}
        </span>
  </div>
  <div class='rard-list-item-actions'>
    {% if can_edit and has_object_lock %}
      <form novalidate class='form-inline' action='{% url "anonymous_fragment:unlink_anonymous_apposita" anonymous_fragment.pk appositum.pk %}' method='POST'>
          {% csrf_token %}
          <div class='form-group'>
              <button type='submit' class='btn btn-link text-danger confirm-delete p-0 ml-2'
                  data-what='appositum link'>{% trans 'Unlink' %}</button>
          </div>
      </form>
    {% endif %}
  </div>
</div>

src/rard/templates/research/partials/appositum_links_list_item.html
{# Assumes a context object named 'link' also 'can_edit' and 'has_object_lock' #}

{% load i18n show_citing_info %}

<div class='rard-list-item d-flex justify-content-between'>
  <div>
      <li class="unstyled">
        {% include 'research/partials/render_definite_indicators.html' with link=link %}
          {% if link.linked_to %}
              {% with fragment=link.linked_to %}
              <span>
                  {% with fragment.get_display_name as link_text %}
                      {% if perms.research.view_fragment %}
                      <a href='{% url "fragment:detail" fragment.pk %}'>{{ link_text }}</a>
                      {% else %}
                          {{ link_text }}
                      {% endif %}
                  {% endwith %}
                  {% include 'research/partials/render_inline_lock_icon.html' with object=fragment %}
              </span>

              {% endwith %}
          {% elif link.work %}
              {% with work=link.work %}
              <a href='{% url "work:detail" work.pk %}'>{{ work }}
                  {% if link.exclusive %}*{% endif %}
              </a>

              {% if book %}
                  book {{ book }}

                  {% if book.display_date_range %}
                      <span class='text-muted'><small>[{{ book.display_date_range }}]</small></span>
                  {% endif %}

              {% else %}
                  {% if work.display_date_range %}
                      <span class='text-muted'><small>[{{ work.display_date_range }}]</small></span>
                  {% endif %}

              {% endif %}

              {% include 'research/partials/render_inline_lock_icon.html' with object=work %}

              {% endwith %}

          {% elif link.antiquarian %}

              {% with antiquarian=link.antiquarian %}
                  {% with antiquarian.name as link_text %}
                      {% if perms.research.view_antiquarian %}
                      <a href='{% url "antiquarian:detail" antiquarian.pk %}'>{{ link_text }}</a>
                      {% else %}
                          {{ link_text }}
                      {% endif %}
                      {% if antiquarian.display_date_range %}
                      <span class='text-muted'><small>[{{ antiquarian.display_date_range }}]</small></span>
                      {% endif %}
                      {% include 'research/partials/render_inline_lock_icon.html' with object=antiquarian %}
                  {% endwith %}
              {% endwith %}


          {% endif %}

      </li>
      {% if link.linked_to %}
          {% with fragment=link.linked_to %}

          <div>
              <div class="card border-0 pt-1 pb-0 bg-transparent card-body">
              <small>
                  <span class='text-muted'>

                      {% with citing_author=citing_author|default:None %}
                      {{ fragment|show_citing_info:citing_author|safe }}
                      {% endwith %}

                      {% comment %}
                      {% if not fragment.get_all_names %}
                          No links
                      {% else %}
                      <ul class='pl-3'>
                          {% for name in fragment.get_all_names %}
                          <li class="unstyled">
                              {{ name }}
                          </li>
                          {% endfor %}
                      </ul>
                      {% endif %}
                      {% endcomment %}
                  </span>
              </small>
              </div>
          </div>
          {% endwith %}
      {% endif %}
  </div>
  <div class='rard-list-item-actions'>
    {% if can_edit and has_object_lock %}
      <form novalidate class='form-inline' action='{% url "anonymous_fragment:unlink_apposita" object.pk link.pk %}' method='POST'>
          {% csrf_token %}
          <div class='form-group'>
              <button type='submit' class='btn btn-link text-danger confirm-delete p-0 ml-2'
                  data-what='appositum link'>{% trans 'Unlink' %}</button>
          </div>
      </form>
    {% endif %}
  </div>
</div>

src/rard/templates/research/partials/comment_list_item.html
{# Assumes a context object named 'comment' #}

{% load i18n humanize %}

<hr>

<p>
    {{ comment.content|linebreaks }}
</p>

<div class="d-flex w-100">
    <div class='mr-auto'>
        <small class='text-muted'>
            {{ comment.user.display_name }} {{ comment.created|naturaltime }}
        </small>
    </div>
    <div class='ml-auto'>
        {% if request.user == comment.user %}
        <form novalidate class='form-inline' action='{% url "delete_comment" comment.pk %}' method='POST'>
            {% csrf_token %}
            <div class='form-group'>
                <button type='submit' class='btn btn-link text-danger confirm-delete p-0'
                    data-what='comment'>{% trans 'Delete' %}</button>
            </div>
        </form>
        {% endif %}
    </div>
</div>

src/rard/templates/research/partials/ordered_anonymousfragment_area.html
{% load i18n %}


<div class='ordered-list parent-ordering-group'>
    {% for object in object_list %}

        {% include 'research/partials/anonymoustopiclink_list_item.html' with link=object can_edit=perms.research.change_fragment %}


    {% endfor %}
</div>

src/rard/templates/research/partials/render_locked_info.html
{# Assumes a context object named 'object' which is a LockableModel instance #}

{% load humanize object_lock i18n %}

    <div class='d-flex justify-content-between align-items-center mb-2'>
        <div class='mr-3'>

            {% include 'research/partials/render_locked_icons.html' %}

        </div>
        <div>
                {% csrf_token %}
                {% if object.locked_by == request.user %}
                <div class="dropdown show">
                    <a class="btn btn-primary btn-sm dropdown-toggle" name='lock' href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                    </a>

                    <div class="dropdown-menu text-center p-2" aria-labelledby="dropdownMenuLink">
                        <form novalidate class='form-group mb-0'  action='{% if is_testimonium %}{% url "testimonium:delete" object.pk %} {% elif is_work %}{% url "work:delete" object.pk %} {% elif is_antiquarian %}{% url "antiquarian:delete" object.pk %}{% elif is_anonymousfragment %}{% url "anonymous_fragment:delete" object.pk %}{% elif is_fragment %}{% url "fragment:delete" object.pk %}{% endif %}'
                            method='POST'>
                            {% csrf_token %}
                            <button type='submit' class='btn btn-link text-danger {% if object.mentioned_in.all %}confirm-delete-mentions {% else %} confirm-delete {% endif %}'
                                data-what='{{is_testimonium}}{{is_work}}{{is_antiquarian}}{{is_anonymousfragment}}{{is_fragment}}'>{% trans 'Delete' %}</button>
                        </form>

                        {% if is_anonymousfragment %}
                        <form novalidate class='form-group mb-0' action='{% url "anonymous_fragment:convert_to_fragment" object.pk %}' method='POST'>
                            {% csrf_token %}
                            <button
                            type='submit'
                            class='
                            {% if object.get_all_links %}has-links{% endif %}
                            btn btn-link text-danger confirm-convert p-1 text-nowrap
                            '
                            data-what='anonymous fragment'
                            >{% trans 'Make non-anonymous' %}</button>
                        </form>
                        <form novalidate class='form-group mb-0' action='{% url "anonymous_fragment:duplicate" object.pk %}' method='POST'>
                            {% csrf_token %}
                            <button type='submit' class='btn btn-link text-info'
                                data-what='anonymous fragment'>{% trans 'Duplicate' %}</button>
                        </form>

                        {% elif is_fragment %}
                            {% if object.is_unlinked %}
                            <form novalidate class='form-group mb-0' action='{% url "fragment:convert_to_anonymous" object.pk %}' method='POST'>
                                {% csrf_token %}
                                <button type='submit' class='btn btn-link text-danger text-nowrap confirm-convert'
                                    data-what='fragment'>{% trans 'Make anonymous' %}</button>
                            </form>
                            <form novalidate class='form-group mb-0' action='{% url "fragment:convert_to_testimonium" object.pk %}' method='POST'>
                                {% csrf_token %}
                                <button type='submit' class='btn btn-link text-danger text-nowrap confirm-convert'
                                    data-what='fragment'>{% trans 'Make testimonium' %}</button>
                            </form>
                            {% endif %}
                            <form novalidate class='form-group mb-0' action='{% url "fragment:duplicate" object.pk %}' method='POST'>
                                {% csrf_token %}
                                <button type='submit' class='btn btn-link text-info'
                                    data-what='fragment'>{% trans 'Duplicate' %}</button>
                            </form>
                        {% elif is_testimonium %}
                            <form novalidate class='form-group mb-0' action='{% url "testimonium:convert_to_fragment" object.pk %}' method='POST'>
                                {% csrf_token %}
                                <button
                                type='submit'
                                class='
                                {% if object.get_all_links %}has-links{% endif %}
                                btn btn-link text-danger confirm-convert p-1 text-nowrap
                                '
                                data-what='testimonium'
                                >{% trans 'Make fragment' %}</button>
                            </form>
                            <form novalidate class='form-group mb-0' action='{% url "testimonium:duplicate" object.pk %}' method='POST'>
                                {% csrf_token %}
                                <button type='submit' class='btn btn-link text-info'
                                    data-what='testimonium'>{% trans 'Duplicate' %}</button>
                            </form>
                        {% endif %}

                        <hr class="m-1">
                        <form novalidate enctype="multipart/form-data" autocomplete='off' action='{{ request.path }}' class="form"
                        method='POST'>
                        {% csrf_token %}
                        <button type='submit' class='btn btn-link text-primary' name='unlock'>Finish Editing</button>
                        </form>
                    </div>
                </div>
                {% else %}
                <form novalidate enctype="multipart/form-data" autocomplete='off' action='{{ request.path }}' class="form"
                method='POST'>
                {% csrf_token %}
                    {% if object.is_locked %}
                        <button type='submit' class='btn btn-warning btn-sm' name='request'>Request Item</button>
                        {% if request.user.can_break_locks %}
                            <button title='You can break this lock'  type='submit' class='btn btn-danger btn-sm' name='break'><i class='fa fa-unlock'></i> Unlock</button>
                        {% endif %}
                    {% elif not object.is_locked %}

                    <div class="dropdown show">
                        <a class="btn btn-primary btn-sm dropdown-toggle" name='lock' href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Edit
                        </a>

                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <button type='submit' name='days' value='1' class='dropdown-item'>for 1 day</button>
                            <button type='submit' name='days' value='2' class='dropdown-item'>for 2 days</button>
                            <button type='submit' name='days' value='7' class='dropdown-item'>for a week</button>
                            <button type='submit' name='lock' class='dropdown-item'>until I unlock</button>
                        </div>
                    </div>
                    {% endif %}
                    </form>
                {% endif %}
        </div>
    </div>
    {% with user_lock_request=request.user|lock_request:object %}
    {% if user_lock_request %}<small class='text-muted'>You requested this item on {{ user_lock_request.created }}</small>{% endif %}
    {% endwith %}