src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views import defaults as default_views

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

base_urlpatterns = [
    path("users/", include("rard.users.urls", namespace="users")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    # research urls
    path("", include("rard.research.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    base_urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        base_urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + base_urlpatterns

prefix = getattr(settings, "URL_PREFIX", "")


urlpatterns = [path("{}".format(prefix), include((base_urlpatterns)))]

src/rard/research/urls.py
from django.conf.urls import include
from django.urls import path

import rard.research.views as views

# common urls for both fragments and testimonia for shared views that we
# want to expose under different namespaces
common_patterns = [
    path(
        "original-text/<pk>/update/",
        views.OriginalTextUpdateView.as_view(),
        name="update_original_text",
    ),
    path(
        "original-text/<pk>/update-author/",
        views.OriginalTextUpdateAuthorView.as_view(),
        name="update_author_original_text",
    ),
    path(
        "original-text/<pk>/delete/",
        views.OriginalTextDeleteView.as_view(),
        name="delete_original_text",
    ),
    path(
        "original-text/<pk>/create-translation/",
        views.TranslationCreateView.as_view(),
        name="create_translation",
    ),
    path(
        "translation/<pk>/update/",
        views.TranslationUpdateView.as_view(),
        name="update_translation",
    ),
    path(
        "translation/<pk>/delete/",
        views.TranslationDeleteView.as_view(),
        name="delete_translation",
    ),
]

# history_patterns = [
#     path("<content_type>/<pk>/history/", views.HistoryView.as_view(), name="history"),
# ]

# app_name = "research"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("ajax/move-link/", views.MoveLinkView.as_view(), name="move_link"),
    path("ajax/move-topic/", views.MoveTopicView.as_view(), name="move_topic"),
    path(
        "ajax/move-anonymoustopiclink/",
        views.MoveAnonymousTopicLinkView.as_view(),
        name="move_anonymoustopiclink",
    ),
    path(
        "ajax/create-apparatus-criticus-line/",
        views.CreateApparatusCriticusLineView.as_view(),
        name="create_apparatus_criticus_line",
    ),
    path(
        "ajax/delete-apparatus-criticus-line/",
        views.DeleteApparatusCriticusLineView.as_view(),
        name="delete_apparatus_criticus_line",
    ),
    path(
        "ajax/update-apparatus-criticus-line/",
        views.UpdateApparatusCriticusLineView.as_view(),
        name="update_apparatus_criticus_line",
    ),
    path(
        "ajax/refresh-original-text-content/",
        views.RefreshOriginalTextContentView.as_view(),
        name="refresh_original_text_content",
    ),
    # path("comment/<pk>/delete/", views.CommentDeleteView.as_view(), name="delete_comment"),
    # path("text-field/<pk>/comments/", views.TextObjectFieldCommentListView.as_view(), name="list_comments_on_text"),
    path(
        "antiquarian/",
        include(
            (
                [
                    path("list/", views.AntiquarianListView.as_view(), name="list"),
                    path(
                        "create/", views.AntiquarianCreateView.as_view(), name="create"
                    ),
                    path("<pk>/", views.AntiquarianDetailView.as_view(), name="detail"),
                    path(
                        "<pk>/introduction/",
                        views.AntiquarianIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/",
                        views.AntiquarianUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.AntiquarianUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "<pk>/bibliography/",
                        views.BibliographySectionView.as_view(),
                        name="bibliography",
                    ),
                    path(
                        "<pk>/refresh_bibliography/",
                        views.refresh_bibliography_from_mentions,
                        name="refresh_bibliography",
                    ),
                    path(
                        "<pk>/delete/",
                        views.AntiquarianDeleteView.as_view(),
                        name="delete",
                    ),
                    path(
                        "<pk>/work/create/",
                        views.AntiquarianWorkCreateView.as_view(),
                        name="create_work",
                    ),
                    path(
                        "<pk>/works/",
                        views.AntiquarianWorksUpdateView.as_view(),
                        name="update_works",
                    ),
                    path(
                        "<pk>/bibliography/create/",
                        views.BibliographyCreateView.as_view(),
                        name="create_bibliography",
                    ),
                    path(
                        "concordance/<pk>/delete/",
                        views.AntiquarianConcordanceDeleteView.as_view(),
                        name="delete_concordance",
                    ),
                ],
                "research",
            ),
            namespace="antiquarian",
        ),
    ),
    path(
        "bibliography/",
        include(
            (
                [
                    path("", views.BibliographyOverviewView.as_view(), name="overview"),
                    path("list/", views.BibliographyListView.as_view(), name="list"),
                    path(
                        "create/",
                        views.BibliographyCreateView.as_view(),
                        name="create",
                    ),
                    path(
                        "create-inline/",
                        views.BibliographyCreateInlineView.as_view(),
                        name="create_inline",
                    ),
                    path(
                        "<pk>/",
                        views.BibliographyDetailView.as_view(),
                        name="detail",
                    ),
                    path(
                        "<pk>/update/",
                        views.BibliographyUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/delete/",
                        views.BibliographyDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "research",
            ),
            namespace="bibliography",
        ),
    ),
    path(
        "work/",
        include(
            (
                [
                    path("list/", views.WorkListView.as_view(), name="list"),
                    path("create/", views.WorkCreateView.as_view(), name="create"),
                    path("<pk>/", views.WorkDetailView.as_view(), name="detail"),
                    path("<pk>/update/", views.WorkUpdateView.as_view(), name="update"),
                    path("<pk>/delete/", views.WorkDeleteView.as_view(), name="delete"),
                    path(
                        "<pk>/create-book/",
                        views.BookCreateView.as_view(),
                        name="create_book",
                    ),
                    path(
                        "book/<pk>/update/",
                        views.BookUpdateView.as_view(),
                        name="update_book",
                    ),
                    path(
                        "book/<pk>/delete/",
                        views.BookDeleteView.as_view(),
                        name="delete_book",
                    ),
                    path(
                        "book/<pk>/introduction/",
                        views.BookIntroductionView.as_view(),
                        name="book_introduction",
                    ),
                    path(
                        "<pk>/introduction/",
                        views.WorkIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.WorkUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "book/<pk>/update/introduction/",
                        views.BookUpdateIntroductionView.as_view(),
                        name="update_book_introduction",
                    ),
                    path(
                        "fetch-books",
                        views.fetch_books,
                        name="fetch_books",
                    ),
                ],
                "research",
            ),
            namespace="work",
        ),
    ),
    path(
        "fragment/",
        include(
            (
                [
                    path("list/", views.FragmentListView.as_view(), name="list"),
                    path("create/", views.FragmentCreateView.as_view(), name="create"),
                    path(
                        "<pk>/update/",
                        views.FragmentUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "update-link/<pk>",
                        views.FragmentUpdateWorkLinkView.as_view(),
                        name="update_fragment_link",
                    ),
                    path(
                        "<pk>/commentary/",
                        views.FragmentCommentaryView.as_view(),
                        name="commentary",
                    ),
                    path(
                        "<pk>/update/commentary/",
                        views.FragmentUpdateCommentaryView.as_view(),
                        name="update_commentary",
                    ),
                    path(
                        "<pk>/update/public-commentary/",
                        views.FragmentUpdatePublicCommentaryView.as_view(),
                        name="update_public_commentary",
                    ),

src/rard/users/urls.py
from django.urls import path

from rard.users.views import user_detail_view, user_update_view

app_name = "users"
urlpatterns = [
    path("update-profile/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

src/rard/research/models/testimonium.py
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from simple_history.models import HistoricalRecords

from rard.research.models.mixins import HistoryModelMixin
from rard.utils.shared_functions import organise_links
from rard.utils.text_processors import make_plain_text

from .base import HistoricalBaseModel, TestimoniumLink


class Testimonium(HistoryModelMixin, HistoricalBaseModel):
    history = HistoricalRecords(
        excluded_fields=[
            "original_texts",
        ]
    )

    def related_lock_object(self):
        return self

    LINK_TYPE = TestimoniumLink

    original_texts = GenericRelation("OriginalText", related_query_name="testimonia")

    def definite_book_links(self):
        return (
            self.antiquarian_testimoniumlinks.filter(
                definite_book=True,
            )
            .order_by("work", "-book")
            .distinct()
        )

    def possible_book_links(self):
        return (
            self.antiquarian_testimoniumlinks.filter(
                definite_book=False,
            )
            .order_by("work", "-book")
            .distinct()
        )

    def definite_work_links(self):
        return (
            self.antiquarian_testimoniumlinks.filter(
                definite_work=True,
            )
            .order_by("work", "-book")
            .distinct()
        )

    def possible_work_links(self):
        return (
            self.antiquarian_testimoniumlinks.filter(
                definite_work=False,
            )
            .order_by("work", "-book")
            .distinct()
        )

    def definite_antiquarian_links(self):
        return self.antiquarian_testimoniumlinks.filter(definite_antiquarian=True)

    def possible_antiquarian_links(self):
        return self.antiquarian_testimoniumlinks.filter(definite_antiquarian=False)

    def get_absolute_url(self):
        return reverse("testimonium:detail", kwargs={"pk": self.pk})

    def get_all_names(self):
        return [link.get_display_name() for link in self.get_all_links()]

    def get_link_names(self, show_certainty=True):
        links = self.get_all_links().order_by(
            "-work__unknown", "work", "antiquarian", "order"
        )
        names = []
        for link in links:
            if link.work and not link.work.unknown:
                name = "%s [= %s]" % (
                    link.get_work_display_name(),
                    link.get_display_name(),
                )
            else:
                name = "%s" % link.get_display_name()
            if show_certainty and not link.definite:
                name += " (possible)"
            names.append(name)
        return names

    def get_all_work_names(self):
        # all the names wrt works
        return [link.get_work_display_name() for link in self.get_all_links()]

    def get_all_links(self):
        return (
            TestimoniumLink.objects.filter(testimonium=self)
            .order_by(
                "antiquarian__name",
                "work__worklink__order",
                "book__unknown",
                "book__order",
            )
            .distinct()
        )

    def get_organised_links(self):
        return organise_links(self)

    def save(self, *args, **kwargs):
        if self.commentary:
            self.plain_commentary = make_plain_text(self.commentary.content)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.get_display_name_option_c()


Testimonium.init_text_object_fields()

src/rard/research/models/topic.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from simple_history.models import HistoricalRecords

from rard.research.models.mixins import HistoryModelMixin
from rard.utils.basemodel import BaseModel, LockableModel, OrderableModel


class Topic(HistoryModelMixin, OrderableModel, LockableModel, BaseModel):
    history = HistoricalRecords()

    def related_lock_object(self):
        return self

    # class Meta:
    #     ordering = ['order']

    name = models.CharField(max_length=128, blank=False, unique=True)

    slug = models.SlugField(max_length=128)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("topic:detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name) or self.slug
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = str(self.pk)
            self.save()

    @property
    def fragments(self):
        # ordered
        return self.fragment_set.all().order_by("topiclink__order")

    def reindex_fragment_links(self):
        # where there has been a change, ensure the
        # ordering of fragments is correct (zero-indexed)
        from django.db import transaction

        from rard.research.models.fragment import TopicLink

        # single db update
        with transaction.atomic():
            links = TopicLink.objects.filter(topic=self).order_by(
                models.F(("order")).asc(nulls_first=False)
            )
            for count, link in enumerate(links):
                link.order = count
                link.save()

src/rard/templates/research/add_appositum_anonymous_link.html
{% extends "research/base.html" %}
{% load i18n bootstrap4 %}

{% block heading %}
    {% blocktrans with name=form.instance.linked_field %}
        Add appositum link to fragment
    {% endblocktrans %}
    {{ form.media.css }}
{% endblock %}

{% block inner %}

    <form novalidate enctype="multipart/form-data" autocomplete='off' action='{{ request.path }}' class="form" method='POST'>
        {% csrf_token %}
        {% bootstrap_field form.anonymous_fragment %}


        <button type="submit" class="btn btn-primary">
            {% trans 'Create' %}
        </button>
        <button name='another' type="submit" class="btn btn-outline-primary">
            {% trans 'Create and add another' %}
        </button>
    </form>
{% endblock %}

src/rard/templates/research/antiquarian_form.html
{% extends "research/base.html" %}
{% load i18n bootstrap4 %}

{% block heading %}
    {% if object %}
        {% trans 'Edit Antiquarian Details' %}
    {% else %}
        {% trans 'Create Antiquarian' %}
    {% endif %}
{% endblock %}

{% block inner %}
    <form novalidate enctype="multipart/form-data" autocomplete='off' action='{{ request.path }}' class="form" method='POST'>
        {% csrf_token %}
        {% bootstrap_field form.name %}
        {% bootstrap_field form.order_name %}
        {% bootstrap_field form.re_code %}
        {% bootstrap_field form.date_range %}
        {% bootstrap_field form.order_year %}

        {% if form.introduction_text %}
            {% bootstrap_field form.introduction_text %}
        {% endif %}

        {% if form.bibliography_items %}
            {% bootstrap_field form.bibliography_items %}
        {% endif %}

      <button type="submit" class="btn btn-primary">
            {% if object %}
                {% trans 'Save' %}
            {% else %}
                {% trans 'Create' %}
            {% endif %}
        </button>
    </form>
{% endblock %}

src/rard/templates/research/citingauthor_detail.html
{% extends "research/detail_base.html" %}
{% load i18n object_lock %}
{% block title %}Citing Author {{object.name}} {% endblock %}

{% block heading %}{{ object }}{% endblock %}

{% block action %}

    {% with request.user|has_lock:object as has_object_lock %}

        {% include 'research/partials/render_locked_info.html' %}

        <div class='d-flex justify-content-end'>
        {% if has_object_lock %}
            {% if perms.research.delete_citingauthor %}
            <form novalidate class='form-inline' action='{% url "citingauthor:delete" object.pk %}' method='POST'>
                {% csrf_token %}
                <div class='form-group'>
                    <button type='submit' class='btn btn-link text-danger confirm-delete p-0 ml-2'
                        data-what='citing author'>{% trans 'Delete' %}</button>
                </div>
            </form>
            {% endif %}
        {% endif %}
        </div>
    {% endwith %}

{% endblock %}


{% block inner %}
    {% with request.user|has_lock:object as has_object_lock %}

    <hr>
    <section>
        <div class='d-flex justify-content-between mb-3'>
            <div>
                <h5>{% trans 'Details' %}</h5>
            </div>
            <div>
                {% if perms.research.change_citingauthor and has_object_lock %}
                <a href='{% url "citingauthor:update" object.pk %}'>{% trans 'Edit' %}</a>
                {% endif %}
            </div>
        </div>

        <dl class="row mb-0">
            <dt class="col-sm-3">{% trans 'Name' %}</dt>
            <dd class="col-sm-9">{{ object.name }}</dd>
            {% if not object.is_anonymous_citing_author %}
            <dt class="col-sm-3">{% trans 'Name for Alphabetisation' %}</dt>
            <dd class="col-sm-9">{{ object.order_name }}</dd>
            {% endif %}
            <dt class="col-sm-3">{% trans 'Relevant Dates' %}</dt>
            <dd class="col-sm-9">
                {{ object.display_date_range|default:'-' }}
            </dd>
            <dt class="col-sm-3">{% trans 'Year for Ordering' %}</dt>
            <dd class="col-sm-9">{{ object.order_year }}</dd>
        </dl>
    </section>

    <hr>
    <section>

        <div class='d-flex justify-content-between w-100'>
            <div>
                <h5 class='mb-3 mr-3'>{% trans 'Introduction' %}</h5>
            </div>
            <div>
                {% if perms.research.change_citingauthor and has_object_lock %}
                <button
                  class="btn text-primary p-0 ml-2"
                  hx-get="{% url 'citingauthor:update_introduction' object.pk %}"
                  hx-target=".introduction-container"
                  hx-swap="innerHTML">{% trans 'Edit' %}</button>
                {% endif %}
            </div>
        </div>
        <div class="introduction-container rich-text-form-container">
            {% include 'research/partials/text_object_preview.html' with text_object=object.introduction %}
        </div>

    </section>
    <hr>

    <section>
        <div class='d-flex justify-content-between mb-3'>
            <div>
                <h5>{% trans 'Works' %}</h5>
            </div>
            <div>
                {% if perms.research.change_citingauthor and has_object_lock %}
                <a href='{% url "citingauthor:create_work_for_author" object.pk %}'>{% trans 'New Work' %}</a>
                {% endif %}
            </div>
        </div>

        {% for work in object.citingwork_set.all %}

            {% include 'research/partials/citingwork_list_item.html' with citingwork=work %}

        {% endfor %}
    </section>

    <hr>

    <section>
        <div class='d-flex justify-content-between mb-3'>
            <div>
                <h5>{% trans 'Linked Material' %}</h5>
            </div>
            <div>
            </div>
        </div>


        <ul>

        {% for text_type, item in ordered_materials %}
            {% if text_type == 'fragment' %}
                {% include 'research/partials/fragment_list_item.html' with fragment=item citing_author=object %}
            {% elif text_type == 'testimonium' %}
                {% include 'research/partials/testimonium_list_item.html' with testimonium=item citing_author=object %}
            {% elif text_type == 'anonymous fragment' %}
                {% include 'research/partials/anonymousfragment_list_item.html' with fragment=item citing_author=object %}
            {% endif %}
        {% endfor %}

        </ul>

    </section>

    <hr>

    <section>
        <div class='d-flex justify-content-between mb-3'>
            <div>
                <h5>{% trans 'Bibliography' %}</h5>
            </div>
            <div>
                {% if perms.research.change_citingauthor and has_object_lock %}
                <a href='{% url "citingauthor:update" object.pk %}'>{% trans 'Add existing' %}</a><p></p>
                <a href='{% url "bibliography:create" %}'>{% trans 'Add new' %}</a>
                {% endif %}
            </div>
        </div>
        {% for item in object.bibliography_items.all %}

        {% include 'research/partials/bibliography_list_item.html' with can_edit=perms.research.change_citingauthor has_object_lock=has_object_lock %}

        {% endfor %}
    </section>

    {% endwith %}

{% endblock %}

src/rard/templates/research/citingauthor_form.html
{% extends "research/base.html" %}
{% load i18n bootstrap4 %}

{% block heading %}
    {% if object %}
        {% trans 'Edit Citing Author Details' %}
    {% else %}
        {% trans 'Create Citing Author' %}
    {% endif %}
{% endblock %}

{% block inner %}
    <form novalidate enctype="multipart/form-data" autocomplete='off' action='{{ request.path }}' class="form" method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}

      <button type="submit" class="btn btn-primary">
            {% if object %}
                {% trans 'Save' %}
            {% else %}
                {% trans 'Create' %}
            {% endif %}
        </button>
        {% if not object %}
            <button type="submit" name='then_add_works' class="btn btn-outline-primary">
            {% trans 'Create and Add Works' %}
            </button>
        {% endif %}
    </form>
{% endblock %}

src/rard/templates/research/citingauthor_full_list.html
{% extends "research/list_base.html" %}
{% load i18n %}

{% block heading %}
    {% trans 'Citing Author Directory' %}
{% endblock %}

{% block action %}
{% endblock %}

{% block inner %}

    {% for object in page_obj %}

    {% include 'research/partials/citingauthor_list_item.html' with citingauthor=object %}

    {% endfor %}

    {{ block.super }}

{% endblock %}

src/rard/templates/research/detail_base.html
{% extends 'research/base.html' %}
{% load i18n get_history %}

{% block outer %}

{{ block.super }}

{% block last_modified %}
<hr>
<p>
    <small>
    {% include 'research/partials/render_last_modified_info.html' with object=object %}
    </small>
</p>
{% endblock %}

{% endblock %}

src/rard/templates/research/home.html
{% extends "research/base.html" %}
{% load i18n get_object_class %}

{% block outer %}
<div class='row'>
    {% if perms.research.add_fragment %}
    <div class='col-md-3 mb-3'>
        <a href='{% url "fragment:create" %}' class='btn btn-block btn-outline-secondary'>{% trans 'Create Fragment' %}</a>
    </div>
    {% endif %}
    {% if perms.research.add_antiquarian %}
    <div class='col-md-3 mb-3'>
        <a href='{% url "antiquarian:create" %}' class='btn btn-block btn-outline-secondary'>{% trans 'Create Antiquarian' %}</a>
    </div>
    {% endif %}
    {% if perms.research.add_testimonium %}
    <div class='col-md-3 mb-3'>
        <a href='{% url "testimonium:create" %}' class='btn btn-block btn-outline-secondary'>{% trans 'Create Testimonium' %}</a>
    </div>
    {% endif %}
    {% if perms.research.add_work %}
    <div class='col-md-3 mb-3'>
        <a href='{% url "work:create" %}' class='btn btn-block btn-outline-secondary'>{% trans 'Create Work' %}</a>
    </div>
    {% endif %}
</div>
<div class='my-5'>
    <p>
        You are currently editing {{ request.user.objectlock_set.count }} item{{ request.user.objectlock_set.count|pluralize }}
    </p>

    <ul class="list-group list-group-flush">
    {% for lock in request.user.objectlock_set.all %}
        <li class="rard-list-item border-0  d-flex justify-content-between align-items-center">
            <div>
                <a class='mr-2' href='{{ lock.content_object.get_absolute_url }}'>{{ lock.content_object|safe }}</a>
                {% include 'research/partials/render_lock_request_info.html' %}
            </div>
            <div>
                <span class='badge badge-secondary badge-pill'>{{ lock.content_object|get_object_class }}</span>
            </div>
        </li>
    {% endfor %}
    </ul>

</div>

{% endblock %}

src/rard/templates/research/topic_detail.html
{% extends "research/detail_base.html" %}
{% load i18n object_lock %}

{% block heading %}{{ object.name }}{% endblock %}

{% block action %}
    {% with request.user|has_lock:object as has_object_lock %}

        {% include 'research/partials/render_locked_info.html' %}

        <div class='d-flex justify-content-end'>
        {% if has_object_lock %}
            {% if perms.research.delete_topic %}
            <form novalidate class='form-inline' action='{% url "topic:delete" topic.slug %}' method='POST'>
                {% csrf_token %}
                <div class='form-group'>
                    <button type='submit' class='btn btn-link text-danger confirm-delete p-0 ml-2'
                        data-what='topic'>{% trans 'Delete' %}</button>
                </div>
            </form>
            {% endif %}
        {% endif %}
        </div>
    {% endwith %}
{% endblock %}

{% block inner %}
    {% with request.user|has_lock:object as has_object_lock %}

    <hr>
    <section>
        <div class='d-flex justify-content-between mb-3'>
            <div>
                <h5>{% trans 'Details' %}</h5>
            </div>
            <div>
                {% if perms.research.change_topic and has_object_lock %}
                <a href='{% url "topic:update" object.slug %}'>{% trans 'Edit' %}</a>
                {% endif %}
            </div>
        </div>

        <dl class="row mb-0">
            <dt class="col-sm-3">{% trans 'Name' %}</dt>
            <dd class="col-sm-9">{{ object.name }}</dd>

        </dl>
    </section>

    <hr>

    <section>
        <div class='d-flex justify-content-between mb-3'>
            <div>
                <h5>{% trans 'Fragments' %}</h5>
            </div>
            <div>
               <form novalidate autocomplete='off' action='{{ request.path }}' class="form" method='GET'>
                    <div class="form-row align-items-center">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text bg-white border-0" for="fragment_order">Order by:</label>
                            </div>
                            <select class="custom-select submit-on-change form-control form-control-sm" id='fragment_order' name='order'>
                                <option value='antiquarian' {% if not order or order == 'antiquarian' %}selected{% endif %}>Antiquarian</option>
                                <option value='citing_author' {% if order == 'citing_author' %}selected{% endif %}>Citing Author</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        {% for fragment in fragments %}

        {% include 'research/partials/fragment_list_item.html' with fragment=fragment %}

        {% endfor %}

        {% for anonymousfragment in anonymous_fragments %}

        {% include 'research/partials/anonymousfragment_list_item.html' with fragment=anonymousfragment %}

        {% endfor %}
    </section>

    {% endwith %}
{% endblock %}