src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views import defaults as default_views

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

base_urlpatterns = [
    path("users/", include("rard.users.urls", namespace="users")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    # research urls
    path("", include("rard.research.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    base_urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        base_urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + base_urlpatterns

prefix = getattr(settings, "URL_PREFIX", "")


urlpatterns = [path("{}".format(prefix), include((base_urlpatterns)))]

src/rard/research/urls.py
from django.conf.urls import include
from django.urls import path

import rard.research.views as views

# common urls for both fragments and testimonia for shared views that we
# want to expose under different namespaces
common_patterns = [
    path(
        "original-text/<pk>/update/",
        views.OriginalTextUpdateView.as_view(),
        name="update_original_text",
    ),
    path(
        "original-text/<pk>/update-author/",
        views.OriginalTextUpdateAuthorView.as_view(),
        name="update_author_original_text",
    ),
    path(
        "original-text/<pk>/delete/",
        views.OriginalTextDeleteView.as_view(),
        name="delete_original_text",
    ),
    path(
        "original-text/<pk>/create-translation/",
        views.TranslationCreateView.as_view(),
        name="create_translation",
    ),
    path(
        "translation/<pk>/update/",
        views.TranslationUpdateView.as_view(),
        name="update_translation",
    ),
    path(
        "translation/<pk>/delete/",
        views.TranslationDeleteView.as_view(),
        name="delete_translation",
    ),
]

# history_patterns = [
#     path("<content_type>/<pk>/history/", views.HistoryView.as_view(), name="history"),
# ]

# app_name = "research"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("ajax/move-link/", views.MoveLinkView.as_view(), name="move_link"),
    path("ajax/move-topic/", views.MoveTopicView.as_view(), name="move_topic"),
    path(
        "ajax/move-anonymoustopiclink/",
        views.MoveAnonymousTopicLinkView.as_view(),
        name="move_anonymoustopiclink",
    ),
    path(
        "ajax/create-apparatus-criticus-line/",
        views.CreateApparatusCriticusLineView.as_view(),
        name="create_apparatus_criticus_line",
    ),
    path(
        "ajax/delete-apparatus-criticus-line/",
        views.DeleteApparatusCriticusLineView.as_view(),
        name="delete_apparatus_criticus_line",
    ),
    path(
        "ajax/update-apparatus-criticus-line/",
        views.UpdateApparatusCriticusLineView.as_view(),
        name="update_apparatus_criticus_line",
    ),
    path(
        "ajax/refresh-original-text-content/",
        views.RefreshOriginalTextContentView.as_view(),
        name="refresh_original_text_content",
    ),
    # path("comment/<pk>/delete/", views.CommentDeleteView.as_view(), name="delete_comment"),
    # path("text-field/<pk>/comments/", views.TextObjectFieldCommentListView.as_view(), name="list_comments_on_text"),
    path(
        "antiquarian/",
        include(
            (
                [
                    path("list/", views.AntiquarianListView.as_view(), name="list"),
                    path(
                        "create/", views.AntiquarianCreateView.as_view(), name="create"
                    ),
                    path("<pk>/", views.AntiquarianDetailView.as_view(), name="detail"),
                    path(
                        "<pk>/introduction/",
                        views.AntiquarianIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/",
                        views.AntiquarianUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.AntiquarianUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "<pk>/bibliography/",
                        views.BibliographySectionView.as_view(),
                        name="bibliography",
                    ),
                    path(
                        "<pk>/refresh_bibliography/",
                        views.refresh_bibliography_from_mentions,
                        name="refresh_bibliography",
                    ),
                    path(
                        "<pk>/delete/",
                        views.AntiquarianDeleteView.as_view(),
                        name="delete",
                    ),
                    path(
                        "<pk>/work/create/",
                        views.AntiquarianWorkCreateView.as_view(),
                        name="create_work",
                    ),
                    path(
                        "<pk>/works/",
                        views.AntiquarianWorksUpdateView.as_view(),
                        name="update_works",
                    ),
                    path(
                        "<pk>/bibliography/create/",
                        views.BibliographyCreateView.as_view(),
                        name="create_bibliography",
                    ),
                    path(
                        "concordance/<pk>/delete/",
                        views.AntiquarianConcordanceDeleteView.as_view(),
                        name="delete_concordance",
                    ),
                ],
                "research",
            ),
            namespace="antiquarian",
        ),
    ),
    path(
        "bibliography/",
        include(
            (
                [
                    path("", views.BibliographyOverviewView.as_view(), name="overview"),
                    path("list/", views.BibliographyListView.as_view(), name="list"),
                    path(
                        "create/",
                        views.BibliographyCreateView.as_view(),
                        name="create",
                    ),
                    path(
                        "create-inline/",
                        views.BibliographyCreateInlineView.as_view(),
                        name="create_inline",
                    ),
                    path(
                        "<pk>/",
                        views.BibliographyDetailView.as_view(),
                        name="detail",
                    ),
                    path(
                        "<pk>/update/",
                        views.BibliographyUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/delete/",
                        views.BibliographyDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "research",
            ),
            namespace="bibliography",
        ),
    ),
    path(
        "work/",
        include(
            (
                [
                    path("list/", views.WorkListView.as_view(), name="list"),
                    path("create/", views.WorkCreateView.as_view(), name="create"),
                    path("<pk>/", views.WorkDetailView.as_view(), name="detail"),
                    path("<pk>/update/", views.WorkUpdateView.as_view(), name="update"),
                    path("<pk>/delete/", views.WorkDeleteView.as_view(), name="delete"),
                    path(
                        "<pk>/create-book/",
                        views.BookCreateView.as_view(),
                        name="create_book",
                    ),
                    path(
                        "book/<pk>/update/",
                        views.BookUpdateView.as_view(),
                        name="update_book",
                    ),
                    path(
                        "book/<pk>/delete/",
                        views.BookDeleteView.as_view(),
                        name="delete_book",
                    ),
                    path(
                        "book/<pk>/introduction/",
                        views.BookIntroductionView.as_view(),
                        name="book_introduction",
                    ),
                    path(
                        "<pk>/introduction/",
                        views.WorkIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.WorkUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "book/<pk>/update/introduction/",
                        views.BookUpdateIntroductionView.as_view(),
                        name="update_book_introduction",
                    ),
                    path(
                        "fetch-books",
                        views.fetch_books,
                        name="fetch_books",
                    ),
                ],
                "research",
            ),
            namespace="work",
        ),
    ),
    path(
        "fragment/",
        include(
            (
                [
                    path("list/", views.FragmentListView.as_view(), name="list"),
                    path("create/", views.FragmentCreateView.as_view(), name="create"),
                    path(
                        "<pk>/update/",
                        views.FragmentUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "update-link/<pk>",
                        views.FragmentUpdateWorkLinkView.as_view(),
                        name="update_fragment_link",
                    ),
                    path(
                        "<pk>/commentary/",
                        views.FragmentCommentaryView.as_view(),
                        name="commentary",
                    ),
                    path(
                        "<pk>/update/commentary/",
                        views.FragmentUpdateCommentaryView.as_view(),
                        name="update_commentary",
                    ),
                    path(
                        "<pk>/update/public-commentary/",
                        views.FragmentUpdatePublicCommentaryView.as_view(),
                        name="update_public_commentary",
                    ),

src/rard/users/urls.py
from django.urls import path

from rard.users.views import user_detail_view, user_update_view

app_name = "users"
urlpatterns = [
    path("update-profile/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

src/rard/research/models/bibliography.py
import re

from django.db import models
from django.urls import reverse
from simple_history.models import HistoricalRecords

from rard.research.models.mixins import HistoryModelMixin
from rard.utils.basemodel import BaseModel, LockableModel


class BibliographyItem(HistoryModelMixin, LockableModel, BaseModel):
    history = HistoricalRecords()

    def related_lock_object(self):
        # overrides HistoryModelMixin.related_lock_object
        return self

    def __str__(self):
        r = self.author_surnames
        if self.year:
            r += " [" + self.year + "]"
        title = re.sub(r"<[^>]*>", " ", self.title)
        return r + ": " + re.sub(r"\s+", " ", title).strip()

    def get_absolute_url(self):
        return reverse("bibliography:detail", kwargs={"pk": self.pk})

    def mention_citation(self):
        r = self.author_surnames
        if self.year:
            r += " [" + self.year + "]"
        return r.strip()

    class Meta:
        ordering = ["author_surnames", "year"]

    # string containing names of authors
    # e.g. Smith P, Jones M
    # ordering will be done on this field
    authors = models.CharField(max_length=512, blank=False)

    # comma-separated list of surnames of the authors, to be used for
    # ordering the entries in the list
    author_surnames = models.CharField(
        max_length=512,
        default="",
        blank=False,
        help_text="Comma-separated list of surnames to be used for ordering",
    )

    year = models.CharField(
        max_length=512,
        default="",
        blank=True,
        help_text="Optional date info to use for second-order " "sorting e.g. 1500a",
    )

    title = models.TextField(default="", blank=False)

src/rard/research/models/comment.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from rard.users.models import User
from rard.utils.basemodel import BaseModel


class Comment(BaseModel):
    class Meta:
        # most recent first
        ordering = ["-created"]

    # comments can be left on various object types
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    parent = GenericForeignKey()

    user = models.ForeignKey(User, on_delete=models.SET(User.get_sentinel_user))

    content = models.TextField(blank=False)

src/rard/research/models/history.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.dispatch import receiver
from simple_history.signals import post_create_historical_record

from rard.users.models import User


class HistoricalRecordLog(models.Model):
    class Meta:
        ordering = ["history_date"]

    def get_sentinel_user():
        from allauth.utils import get_user_model

        return get_user_model().objects.get_or_create(
            username="deleted", first_name="Deleted", last_name="User"
        )[0]

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    # auto-deletes e.g. when the history records are pruned
    history_record = GenericForeignKey()

    history_user = models.ForeignKey(
        User,
        related_name="history_log",
        default=None,
        null=True,
        on_delete=models.SET(get_sentinel_user),
    )
    history_date = models.DateTimeField(editable=False)


@receiver(post_create_historical_record)
def post_create_historical_record_callback(sender, **kwargs):
    HistoricalRecordLog.objects.create(
        history_record=kwargs.get("history_instance"),
        history_user=kwargs.get("history_user"),
        history_date=kwargs.get("history_date"),
    )

src/rard/research/models/image.py
from django.conf import settings
from django.db import models

from rard.utils.basemodel import BaseModel


class Image(BaseModel):
    title = models.CharField(max_length=128, blank=False)

    description = models.CharField(max_length=128, blank=True)

    credit = models.CharField(max_length=128, blank=True)

    copyright_status = models.CharField(max_length=128, blank=True)

    name_and_attribution = models.CharField(max_length=128, blank=True)

    public_release = models.BooleanField(default=False)

    upload = models.ImageField(upload_to=settings.UPLOAD_FOLDER, blank=False)

    def __str__(self):
        return self.title

src/rard/research/models/reference.py
from django.db import models


class Reference(models.Model):
    # e.g. Jones/James
    editor = models.CharField(max_length=128, blank=True)

    # The value to be used to refer to the position in the text
    # In some cases it will be a dot-separated list of numbers eg. 2.6-8
    reference_position = models.CharField(blank=False, max_length=128)

    original_text = models.ForeignKey(
        "OriginalText",
        on_delete=models.CASCADE,
        default=None,
        related_name="references",
    )

src/rard/templates/research/partials/section/duplicates_section.html
{% load i18n %}
<section id="duplicates">
    <div class='d-flex justify-content-between mb-3'>
        <div>
            <h5>{% trans 'Duplicates' %}</h5>
            <p class="text-muted">The following items are duplicates</p>
        </div>
    </div>
    {% for duplicate in object.duplicates_list %}
        <li class="pb-2" style="list-style-type:circle;"><a href="{{ duplicate.get_absolute_url }}">{{ duplicate }}</a></li>
    {% endfor %}
</section>

src/rard/templates/research/partials/section/mentions_section.html
{% load i18n %}
<section id="mentions">
    <div class='d-flex justify-content-between mb-3'>
        <div>
            <h5>{% trans 'Mentions' %}</h5>
            <p class="text-muted">This {{obj_name}} was mentioned in the following items</p>
        </div>
    </div>
    {% for mention in object.mentioned_in_list %}
        <li class="pb-2" style="list-style-type:circle;"><a href="{{ mention.get_absolute_url }}">{{ mention }}</a></li>
    {% endfor %}
</section>

src/rard/templates/research/partials/section/original_text_details.html
{# Assumes context objects named 'original_text', 'can_edit' and 'has_object_lock' and 'show_concordances' #}

{% load i18n %}

<dl class="row mb-0">
    <dt class="col-sm-3">{% trans 'Citing Work' %}</dt>
    <dd class="col-sm-9">
        {% if original_text.citing_work %}

            {% if original_text.citing_work.author %}
                <a href='{% url "citingauthor:detail" original_text.citing_work.author.pk %}'>{{ original_text.citing_work.author }}</a>,
            {% else %}
            Unknown,
            {% endif %}
            <a href='{% url "citingauthor:work_detail" original_text.citing_work.pk %}'>{{ original_text.citing_work.title }}</a>
        {% else %}
        -
        {% endif %}
    </dd>

    <dt class="col-sm-3">{% trans 'References' %}</dt>
    <dd class="col-sm-9">
    {{original_text.reference_list}}
    </dd>

{% comment %}
    {# to restore the legacy apparatus criticus entry uncommment this block #}
    <dt class="col-sm-3">{% trans 'Apparatus Criticus' %}</dt>
    <dd class="col-sm-9">{{ original_text.apparatus_criticus|safe|default:'-'|linebreaks }}</dd>
{% endcomment %}

    <dt class="col-sm-3">{% trans 'Apparatus Criticus' %}</dt>
    <dd class="col-sm-9">
        <div>
            {% for line in original_text.apparatus_criticus_lines %}
               <a href='#{{ line.get_anchor_id }}'>{{ line.order|add:1 }}</a>&nbsp;{{ line.content|safe }} {% if not forloop.last %}|{% endif %}
            {% endfor %}
            {% if not original_text.apparatus_criticus_lines %}
              {% if original_text.apparatus_criticus_blank %}
                No apparatus criticus exists for this original text.
              {% else %}
                <div class="alert alert-warning">No apparatus criticus; confirmation needed.</div>
              {% endif %}
            {% endif %}
        </div>
    </dd>

</dl>


    {% if show_concordances %}
    {% if original_text.concordances.count != 0 %}
    <dl class="row mb-0">
        <dt class="col-sm-3">{% trans 'Old Concordances' %}</dt>
        <dd class="col-sm-7">
    <div>

            {% for c in original_text.concordances.all %}
            <div class='d-flex justify-content-between mb-3'>
            {% if can_edit and has_object_lock %}
            <form novalidate class='form-inline' action='{% url "concordance:delete_old" c.pk %}' method='POST'>
                {% csrf_token %}
                <small>{{c}}</small>
                    {% if perms.research.delete_concordance %}
                    <button type='submit' class='btn btn-link text-danger confirm-delete p-0 ml-2'
                        data-what='concordance'>{% trans 'Delete' %}</button>
                    {% endif %}
            </form>
            {% endif %}
            </div>
            {% endfor %}

            </div>
        </dd>
    </dl>
    {% endif %}

{% comment %} New Concordances {% endcomment %}
    <dl class="row mb-0">
        <dt class="col-sm-3">{% trans 'Concordances' %}</dt>
        <dd class="col-sm-7">

                {% if original_text.concordance_models.count == 0 %}
                None
                {% endif %}

            {% for concordance in original_text.concordance_models.all %}
                <div class='d-flex justify-content-between mb-3'>
                <div>{{ concordance }} </div>
                <div>
                    {% if can_edit and has_object_lock %}
                    <form novalidate class='form-inline' action='{% url "concordance:delete" concordance.pk %}' method='POST'>
                        {% csrf_token %}
                        <div class='form-row align-items-center'>
                            {% if perms.research.change_concordance %}
                            <a href='{% url "concordance:update" concordance.pk %}' {% if object.duplicate_frags.all %}class="alert-duplicates" {% endif %}>Edit</a>
                            {% endif %}
                            {% if perms.research.delete_concordance %}
                            <button type='submit' class='btn btn-link text-danger confirm-delete p-0 ml-2'
                                data-what='concordance'>{% trans 'Delete' %}</button>
                            {% endif %}
                            <a class='ml-2' href='{{ concordance.history_url }}'><small><i class='fas fa-list'></i> Changelog</small></a>
                        </div>
                    </form>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </dd>
        {% if can_edit and has_object_lock and perms.research.add_concordance %}
        <dd class="col-sm-2 actions"><a style='float:right' href='{% url "concordance:create" original_text.pk %}'>Add</a></dd>
        {% endif %}
    </dl>
    {% endif %}
    <dl class="row mb-0">

        <dt class="col-sm-3">{% trans 'Translations' %}</dt>
        <dd class="col-sm-7">{{ original_text.translation_set.count|default:'None' }}</dd>
        {% if can_edit and has_object_lock and perms.research.add_translation %}
        <dd class="col-sm-2 actions">
        <a style='float:right' href='{% url "fragment:create_translation" original_text.pk %}'>{% trans 'Add' %}</a>
        </dd>

    </dl>

    {% endif %}