src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.views import defaults as default_views

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

base_urlpatterns = [
    path("users/", include("rard.users.urls", namespace="users")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            html_email_template_name="registration/password_reset_email.html"
        ),
    ),
    path("accounts/", include("django.contrib.auth.urls")),
    # research urls
    path("", include("rard.research.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    base_urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        base_urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + base_urlpatterns

prefix = getattr(settings, "URL_PREFIX", "")


urlpatterns = [path("{}".format(prefix), include((base_urlpatterns)))]

src/rard/research/urls.py
from django.conf.urls import include
from django.urls import path

import rard.research.views as views

# common urls for both fragments and testimonia for shared views that we
# want to expose under different namespaces
common_patterns = [
    path(
        "original-text/<pk>/update/",
        views.OriginalTextUpdateView.as_view(),
        name="update_original_text",
    ),
    path(
        "original-text/<pk>/update-author/",
        views.OriginalTextUpdateAuthorView.as_view(),
        name="update_author_original_text",
    ),
    path(
        "original-text/<pk>/delete/",
        views.OriginalTextDeleteView.as_view(),
        name="delete_original_text",
    ),
    path(
        "original-text/<pk>/create-translation/",
        views.TranslationCreateView.as_view(),
        name="create_translation",
    ),
    path(
        "translation/<pk>/update/",
        views.TranslationUpdateView.as_view(),
        name="update_translation",
    ),
    path(
        "translation/<pk>/delete/",
        views.TranslationDeleteView.as_view(),
        name="delete_translation",
    ),
]

# history_patterns = [
#     path("<content_type>/<pk>/history/", views.HistoryView.as_view(), name="history"),
# ]

# app_name = "research"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("ajax/move-link/", views.MoveLinkView.as_view(), name="move_link"),
    path("ajax/move-topic/", views.MoveTopicView.as_view(), name="move_topic"),
    path(
        "ajax/move-anonymoustopiclink/",
        views.MoveAnonymousTopicLinkView.as_view(),
        name="move_anonymoustopiclink",
    ),
    path(
        "ajax/create-apparatus-criticus-line/",
        views.CreateApparatusCriticusLineView.as_view(),
        name="create_apparatus_criticus_line",
    ),
    path(
        "ajax/delete-apparatus-criticus-line/",
        views.DeleteApparatusCriticusLineView.as_view(),
        name="delete_apparatus_criticus_line",
    ),
    path(
        "ajax/update-apparatus-criticus-line/",
        views.UpdateApparatusCriticusLineView.as_view(),
        name="update_apparatus_criticus_line",
    ),
    path(
        "ajax/refresh-original-text-content/",
        views.RefreshOriginalTextContentView.as_view(),
        name="refresh_original_text_content",
    ),
    # path("comment/<pk>/delete/", views.CommentDeleteView.as_view(), name="delete_comment"),
    # path("text-field/<pk>/comments/", views.TextObjectFieldCommentListView.as_view(), name="list_comments_on_text"),
    path(
        "antiquarian/",
        include(
            (
                [
                    path("list/", views.AntiquarianListView.as_view(), name="list"),
                    path(
                        "create/", views.AntiquarianCreateView.as_view(), name="create"
                    ),
                    path("<pk>/", views.AntiquarianDetailView.as_view(), name="detail"),
                    path(
                        "<pk>/introduction/",
                        views.AntiquarianIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/",
                        views.AntiquarianUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.AntiquarianUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "<pk>/bibliography/",
                        views.BibliographySectionView.as_view(),
                        name="bibliography",
                    ),
                    path(
                        "<pk>/refresh_bibliography/",
                        views.refresh_bibliography_from_mentions,
                        name="refresh_bibliography",
                    ),
                    path(
                        "<pk>/delete/",
                        views.AntiquarianDeleteView.as_view(),
                        name="delete",
                    ),
                    path(
                        "<pk>/work/create/",
                        views.AntiquarianWorkCreateView.as_view(),
                        name="create_work",
                    ),
                    path(
                        "<pk>/works/",
                        views.AntiquarianWorksUpdateView.as_view(),
                        name="update_works",
                    ),
                    path(
                        "<pk>/bibliography/create/",
                        views.BibliographyCreateView.as_view(),
                        name="create_bibliography",
                    ),
                    path(
                        "concordance/<pk>/delete/",
                        views.AntiquarianConcordanceDeleteView.as_view(),
                        name="delete_concordance",
                    ),
                ],
                "research",
            ),
            namespace="antiquarian",
        ),
    ),
    path(
        "bibliography/",
        include(
            (
                [
                    path("", views.BibliographyOverviewView.as_view(), name="overview"),
                    path("list/", views.BibliographyListView.as_view(), name="list"),
                    path(
                        "create/",
                        views.BibliographyCreateView.as_view(),
                        name="create",
                    ),
                    path(
                        "create-inline/",
                        views.BibliographyCreateInlineView.as_view(),
                        name="create_inline",
                    ),
                    path(
                        "<pk>/",
                        views.BibliographyDetailView.as_view(),
                        name="detail",
                    ),
                    path(
                        "<pk>/update/",
                        views.BibliographyUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "<pk>/delete/",
                        views.BibliographyDeleteView.as_view(),
                        name="delete",
                    ),
                ],
                "research",
            ),
            namespace="bibliography",
        ),
    ),
    path(
        "work/",
        include(
            (
                [
                    path("list/", views.WorkListView.as_view(), name="list"),
                    path("create/", views.WorkCreateView.as_view(), name="create"),
                    path("<pk>/", views.WorkDetailView.as_view(), name="detail"),
                    path("<pk>/update/", views.WorkUpdateView.as_view(), name="update"),
                    path("<pk>/delete/", views.WorkDeleteView.as_view(), name="delete"),
                    path(
                        "<pk>/create-book/",
                        views.BookCreateView.as_view(),
                        name="create_book",
                    ),
                    path(
                        "book/<pk>/update/",
                        views.BookUpdateView.as_view(),
                        name="update_book",
                    ),
                    path(
                        "book/<pk>/delete/",
                        views.BookDeleteView.as_view(),
                        name="delete_book",
                    ),
                    path(
                        "book/<pk>/introduction/",
                        views.BookIntroductionView.as_view(),
                        name="book_introduction",
                    ),
                    path(
                        "<pk>/introduction/",
                        views.WorkIntroductionView.as_view(),
                        name="introduction",
                    ),
                    path(
                        "<pk>/update/introduction/",
                        views.WorkUpdateIntroductionView.as_view(),
                        name="update_introduction",
                    ),
                    path(
                        "book/<pk>/update/introduction/",
                        views.BookUpdateIntroductionView.as_view(),
                        name="update_book_introduction",
                    ),
                    path(
                        "fetch-books",
                        views.fetch_books,
                        name="fetch_books",
                    ),
                ],
                "research",
            ),
            namespace="work",
        ),
    ),
    path(
        "fragment/",
        include(
            (
                [
                    path("list/", views.FragmentListView.as_view(), name="list"),
                    path("create/", views.FragmentCreateView.as_view(), name="create"),
                    path(
                        "<pk>/update/",
                        views.FragmentUpdateView.as_view(),
                        name="update",
                    ),
                    path(
                        "update-link/<pk>",
                        views.FragmentUpdateWorkLinkView.as_view(),
                        name="update_fragment_link",
                    ),
                    path(
                        "<pk>/commentary/",
                        views.FragmentCommentaryView.as_view(),
                        name="commentary",
                    ),
                    path(
                        "<pk>/update/commentary/",
                        views.FragmentUpdateCommentaryView.as_view(),
                        name="update_commentary",
                    ),
                    path(
                        "<pk>/update/public-commentary/",
                        views.FragmentUpdatePublicCommentaryView.as_view(),
                        name="update_public_commentary",
                    ),

src/rard/users/urls.py
from django.urls import path

from rard.users.views import user_detail_view, user_update_view

app_name = "users"
urlpatterns = [
    path("update-profile/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

src/rard/research/models/bibliography.py
import re

from django.db import models
from django.urls import reverse
from simple_history.models import HistoricalRecords

from rard.research.models.mixins import HistoryModelMixin
from rard.utils.basemodel import BaseModel, LockableModel


class BibliographyItem(HistoryModelMixin, LockableModel, BaseModel):
    history = HistoricalRecords()

    def related_lock_object(self):
        # overrides HistoryModelMixin.related_lock_object
        return self

    def __str__(self):
        r = self.author_surnames
        if self.year:
            r += " [" + self.year + "]"
        title = re.sub(r"<[^>]*>", " ", self.title)
        return r + ": " + re.sub(r"\s+", " ", title).strip()

    def get_absolute_url(self):
        return reverse("bibliography:detail", kwargs={"pk": self.pk})

    def mention_citation(self):
        r = self.author_surnames
        if self.year:
            r += " [" + self.year + "]"
        return r.strip()

    class Meta:
        ordering = ["author_surnames", "year"]

    # string containing names of authors
    # e.g. Smith P, Jones M
    # ordering will be done on this field
    authors = models.CharField(max_length=512, blank=False)

    # comma-separated list of surnames of the authors, to be used for
    # ordering the entries in the list
    author_surnames = models.CharField(
        max_length=512,
        default="",
        blank=False,
        help_text="Comma-separated list of surnames to be used for ordering",
    )

    year = models.CharField(
        max_length=512,
        default="",
        blank=True,
        help_text="Optional date info to use for second-order " "sorting e.g. 1500a",
    )

    title = models.TextField(default="", blank=False)

src/rard/research/models/comment.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from rard.users.models import User
from rard.utils.basemodel import BaseModel


class Comment(BaseModel):
    class Meta:
        # most recent first
        ordering = ["-created"]

    # comments can be left on various object types
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    parent = GenericForeignKey()

    user = models.ForeignKey(User, on_delete=models.SET(User.get_sentinel_user))

    content = models.TextField(blank=False)

src/rard/research/models/history.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.dispatch import receiver
from simple_history.signals import post_create_historical_record

from rard.users.models import User


class HistoricalRecordLog(models.Model):
    class Meta:
        ordering = ["history_date"]

    def get_sentinel_user():
        from allauth.utils import get_user_model

        return get_user_model().objects.get_or_create(
            username="deleted", first_name="Deleted", last_name="User"
        )[0]

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)

    object_id = models.PositiveIntegerField()

    # auto-deletes e.g. when the history records are pruned
    history_record = GenericForeignKey()

    history_user = models.ForeignKey(
        User,
        related_name="history_log",
        default=None,
        null=True,
        on_delete=models.SET(get_sentinel_user),
    )
    history_date = models.DateTimeField(editable=False)


@receiver(post_create_historical_record)
def post_create_historical_record_callback(sender, **kwargs):
    HistoricalRecordLog.objects.create(
        history_record=kwargs.get("history_instance"),
        history_user=kwargs.get("history_user"),
        history_date=kwargs.get("history_date"),
    )

src/rard/research/models/image.py
from django.conf import settings
from django.db import models

from rard.utils.basemodel import BaseModel


class Image(BaseModel):
    title = models.CharField(max_length=128, blank=False)

    description = models.CharField(max_length=128, blank=True)

    credit = models.CharField(max_length=128, blank=True)

    copyright_status = models.CharField(max_length=128, blank=True)

    name_and_attribution = models.CharField(max_length=128, blank=True)

    public_release = models.BooleanField(default=False)

    upload = models.ImageField(upload_to=settings.UPLOAD_FOLDER, blank=False)

    def __str__(self):
        return self.title

src/rard/research/models/reference.py
from django.db import models


class Reference(models.Model):
    # e.g. Jones/James
    editor = models.CharField(max_length=128, blank=True)

    # The value to be used to refer to the position in the text
    # In some cases it will be a dot-separated list of numbers eg. 2.6-8
    reference_position = models.CharField(blank=False, max_length=128)

    original_text = models.ForeignKey(
        "OriginalText",
        on_delete=models.CASCADE,
        default=None,
        related_name="references",
    )

src/rard/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Home{% endblock title %} | FRRAnt</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The Republican Antiquarians Research Database Project">
    <meta name="author" content="UCL">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/icon.svg' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://unpkg.com/htmx.org@1.9.2" integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/hyperscript.org@0.9.8"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Noto+Serif&display=swap" rel="stylesheet">

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/alphabetum.css' %}" rel="stylesheet">

    {% if not PRODUCTION_INSTANCE %}
    <!-- Styling to make it obvious we're not in production -->
    <link href="{% static 'css/development.css' %}" rel="stylesheet">
    {% endif %}

    {% endblock %}

    {% block head %}
    {% endblock %}
  </head>

  <body class="subtle-bg">

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-stone justify-content-around">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand ml-5" href="{% url 'home' %}">
          {% trans "The Fragments of the Roman Republican Antiquarians Research Database (FRRAnt)" %}

          {% if not PRODUCTION_INSTANCE %}
            (NON PRODUCTION VERSION)
            <div class="non-prod-column"></div>
          {% endif %}
        </a>

        <div class="collapse navbar-collapse ml-auto mr-5" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>

            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              {% if request.user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">{% trans "Log Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a id="log-in-link" class="nav-link" href="{% url 'login' %}">{% trans "Log In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container mt-5 content-area">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

      <script src="{%static 'js/ckeditor/ckeditor.js'%}"></script>

      <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.min.js"></script>

      <!-- urls provided to project.js -->
      <script>
        const g_mention_url = '{% url "search:mention" %}';
        const g_apparatus_criticus_url = '{% url "search:apparatus_criticus" %}';
        const g_update_apparatus_criticus_url = '{% url "update_apparatus_criticus_line" %}';
        const g_create_apparatus_criticus_url = '{% url "create_apparatus_criticus_line" %}';
        const g_delete_apparatus_criticus_url = '{% url "delete_apparatus_criticus_line" %}';
        const g_refresh_original_text_content_url = '{% url "refresh_original_text_content" %}';
        const g_move_link_url = '{% url "move_link" %}';
        const g_move_topic_url = '{% url "move_topic" %}';
        const g_move_anonymoustopiclink_url = '{% url "move_anonymoustopiclink" %}';
      </script>
      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'js/app-crit-editor.js' %}" async defer></script>
      <script src="{% static 'js/text-editor.js' %}" async defer></script>


    {% endblock javascript %}
  </body>
</html>